(() => {
'use strict';
const $=id=>document.getElementById(id), year=2026;
const dateFromDay=n=>new Date(Date.UTC(year,0,n));
const isoDate=n=>dateFromDay(n).toISOString().slice(0,10);
const dayNumber=date=>Math.round((Date.parse(date+'T00:00:00Z')-Date.UTC(year,0,1))/86400000)+1;
const now=new Date(); let selectedDay=now.getFullYear()===year?Math.floor((Date.UTC(year,now.getMonth(),now.getDate())-Date.UTC(year,0,1))/86400000)+1:1;
let selectedMonth=dateFromDay(selectedDay).getUTCMonth(), requestSequence=0; const loadedDays=new Map();
window.__dailyDevotionalsReady=entries=>entries.forEach(item=>loadedDays.set(item.day,item));
const months=Array.from({length:12},(_,m)=>new Date(Date.UTC(year,m,1)).toLocaleString('en-GB',{month:'long',timeZone:'UTC'}));
function node(tag,content,cls){const e=document.createElement(tag);if(content!=null)e.textContent=String(content);if(cls)e.className=cls;return e;}
function render(item){const p=$('devotionPanel');p.replaceChildren();if(!item){p.append(node('p','This devotional could not be loaded.','note'));return;}
 const head=node('div',null,'readHeading'); head.append(node('span',`DAY ${item.day} · ${new Date(item.date+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}`,'eyebrow'),node('h2',item.title),node('p',item.bible_reading,'scripture'));p.append(head);
 const prose=node('div',null,'devotionalProse'); item.devotional_reflection.split(/\n\n+/).forEach(x=>prose.append(node('p',x))); p.append(prose);
 const close=node('div',null,'quietLines'); close.append(node('p','🙏 '+item.prayer,'prayerLine'),node('p','📖 '+item.memory_verse_reference,'memoryLine'),node('p','🎵 '+item.suggested_hymn_title+(item.suggested_hymn_author?' — '+item.suggested_hymn_author:''),'hymnLine'),node('p','🎯 '+item.focus_point,'focusLine'));p.append(close,node('p','Read the listed passage in your Bible and consider the reflection in its wider scriptural context. Hymn lyrics and copyrighted Bible text are not reproduced here.','note'));
}
function refresh(){ $('dayPicker').value=isoDate(selectedDay);$('dayCounter').textContent=`Day ${selectedDay} of 365`;$('previousDay').disabled=selectedDay===1;$('nextDay').disabled=selectedDay===365;const m=dateFromDay(selectedDay).getUTCMonth();if(m!==selectedMonth)showMonth(m);document.querySelectorAll('#calendarDays .day').forEach(b=>b.classList.toggle('selected',+b.dataset.day===selectedDay)); }
function loadDay(day){day=Math.max(1,Math.min(365,Math.round(+day)||1));selectedDay=day;refresh();$('devotionPanel').replaceChildren(node('p','Opening the devotional…','note'));const req=++requestSequence;if(loadedDays.has(day)){render(loadedDays.get(day));return;}const month=dateFromDay(day).getUTCMonth()+1,s=document.createElement('script');s.src=`readings/month-${String(month).padStart(2,'0')}.js`;s.async=true;s.onerror=()=>{if(req===requestSequence)$('devotionPanel').replaceChildren(node('p','The monthly reading file could not be opened. Upload the complete readings folder.','note'));s.remove();};s.onload=()=>{if(req===requestSequence)render(loadedDays.get(selectedDay));s.remove();};document.head.append(s);}
function showMonth(m){selectedMonth=m;document.querySelectorAll('#months .month').forEach((b,i)=>b.classList.toggle('selected',i===m));const c=$('calendarDays');c.replaceChildren();const count=new Date(Date.UTC(year,m+1,0)).getUTCDate();for(let d=1;d<=count;d++){const n=dayNumber(`${year}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`),b=node('button',d,'day');b.type='button';b.dataset.day=n;b.addEventListener('click',()=>{loadDay(n);location.hash='devotion';});c.append(b);}document.querySelectorAll('#calendarDays .day').forEach(b=>b.classList.toggle('selected',+b.dataset.day===selectedDay));}
months.forEach((m,i)=>{const b=node('button',m,'month');b.type='button';b.addEventListener('click',()=>showMonth(i));$('months').append(b);});showMonth(selectedMonth);$('readDay').addEventListener('click',()=>$('dayPicker').value&&loadDay(dayNumber($('dayPicker').value)));$('dayPicker').addEventListener('change',()=>$('dayPicker').value&&loadDay(dayNumber($('dayPicker').value)));$('previousDay').addEventListener('click',()=>loadDay(selectedDay-1));$('nextDay').addEventListener('click',()=>loadDay(selectedDay+1));loadDay(selectedDay);
})();